FROM 172.16.69.11/moji/centos7
MAINTAINER yw
RUN rm -rf /etc/localtime && ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN mkdir -p /opt
ADD ./<PROJECT>/ /opt/<PROJECT>/
ADD ./jdk1.7.0_21 /opt/jdk1.7.0_21
ADD ./run.sh /opt/
RUN chmod +x /opt/run.sh
ENV   LC_ALL en_US.UTF-8
CMD /opt/run.sh